export { default as LoginModal } from './LoginModal';
export { default as ChangePasswordModal } from './ChangePasswordModal';
export { default as DeleteAccountModal } from './DeleteAccountModal';
export { default as RegisterModal } from './RegisterModal';
export { default as CompareListModal } from './CompareListModal';
export { default as RecoverPasswordModal } from './RecoverPasswordModal';
export { default as WriteReviewModal } from './WriteReviewModal';
export { default as ReplyModal } from './ReplyModal';
export { default as CartModal } from './CartModal';
export { default as ChangeAvatarModal } from './ChangeAvatarModal';

export * from './LoginModal';
export * from './ChangePasswordModal';
export * from './DeleteAccountModal';
export * from './RegisterModal';
export * from './CompareListModal';
export * from './RecoverPasswordModal';
export * from './WriteReviewModal';
export * from './ReplyModal';
export * from './CartModal';
export * from './ChangeAvatarModal';
